### PR TITLE
Add tests for the neutral laws for the pair monoid

### PR DESCRIPTION
**Pull request by yallop**
The tests are currently failing.  I haven't yet investigated why.

### CODE REVIEW

**Comment by gallais** [comment]
Should the goal be a `<~>` rather than a propositional equality?

**Comment by yallop** [comment]
It should, indeed!  Thanks.  The tests still don't pass, but the problem seems to be the familiar failure to find an implementation for `UltListEquality`.

**Comment by ohad** [comment]
Not sure. These are very high-order terms. If you construct the environment explicitly, can it find the equality proof?

**Comment by ohad** [comment]
Yes, we need auto search to find:
```idris
%hint
public export
Reflexive : (a : Setoid) -> (x : U a) ->  a.equivalence.relation x x 
Reflexive a x = a.equivalence.reflexive x
```
but the issue is that it can't reconstruct the appropriate setoid by unification nor `auto` search here.

One workaround is to require the extended algebra to have an `auto`-findable reflexivity proof.
But I wish we could solve it in one place generally, rather than at each instance.

**Comment by yallop** [comment]
80ef436 adds explicit proof terms so that the tests pass.

**Pull request merged**
